create table if not exists public.family_notifications (
  id bigint generated by default as identity primary key,
  family_id uuid references public.family_units on delete cascade not null,
  recipient_user_id uuid references public.profiles(id) on delete cascade not null,
  actor_user_id uuid references public.profiles(id) on delete set null,
  title text not null,
  body text not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_family_notifications_recipient_read
  on public.family_notifications (recipient_user_id, read_at, created_at desc);

alter table public.family_notifications disable row level security;
