-- SQL migration for creating public.ingredient_mappings table

create table if not exists public.ingredient_mappings (
  id bigint generated by default as identity primary key,
  family_id uuid references public.family_units(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  ingredient_name text not null,
  product_name text not null,
  price numeric(10, 2) not null,
  package_qty numeric(10, 2) not null,
  package_unit text not null,
  supermarket_id text not null,
  reference_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint ingredient_mappings_target_check check (
    (family_id is not null and user_id is null) or
    (family_id is null and user_id is not null)
  ),
  constraint ingredient_mappings_unique_family unique (family_id, ingredient_name),
  constraint ingredient_mappings_unique_user unique (user_id, ingredient_name)
);

-- Enable Row Level Security (RLS)
alter table public.ingredient_mappings enable row level security;

-- Create RLS policies
drop policy if exists user_ingredient_mappings_access on public.ingredient_mappings;
create policy user_ingredient_mappings_access on public.ingredient_mappings
    for all
    using (
        (user_id = auth.uid()) or
        exists (
            select 1 from public.family_members
            where family_members.family_id = public.ingredient_mappings.family_id and family_members.user_id = auth.uid()
        )
    )
    with check (
        (user_id = auth.uid()) or
        exists (
            select 1 from public.family_members
            where family_members.family_id = public.ingredient_mappings.family_id and family_members.user_id = auth.uid()
        )
    );
