-- 1. Create ingredients table if not exists
CREATE TABLE IF NOT EXISTS public.ingredients (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS public_ingredients_read ON public.ingredients;
CREATE POLICY public_ingredients_read ON public.ingredients FOR SELECT USING (true);
DROP POLICY IF EXISTS authenticated_ingredients_write ON public.ingredients;
CREATE POLICY authenticated_ingredients_write ON public.ingredients FOR ALL TO authenticated USING (true);

-- 2. Add new columns to public.recipes
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS meal_type text CHECK (meal_type in ('desayuno', 'comida', 'cena'));
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS price text CHECK (price in ('economica', 'cara'));
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS difficulty text CHECK (difficulty in ('facil', 'intermedia', 'dificil'));
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS health text CHECK (health in ('saludable', 'no saludable'));
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS diet_type text;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS allergens text[] NOT NULL DEFAULT '{}'::text[];
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS instructions text[] NOT NULL DEFAULT '{}'::text[];

-- 3. Create recipe_ingredients junction table
CREATE TABLE IF NOT EXISTS public.recipe_ingredients (
  recipe_id bigint references public.recipes(id) on delete cascade not null,
  ingredient_id bigint references public.ingredients(id) on delete cascade not null,
  quantity numeric not null,
  unit text not null,
  primary key (recipe_id, ingredient_id)
);
ALTER TABLE public.recipe_ingredients ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS public_recipe_ingredients_read ON public.recipe_ingredients;
CREATE POLICY public_recipe_ingredients_read ON public.recipe_ingredients FOR SELECT USING (true);
DROP POLICY IF EXISTS authenticated_recipe_ingredients_write ON public.recipe_ingredients;
CREATE POLICY authenticated_recipe_ingredients_write ON public.recipe_ingredients FOR ALL TO authenticated USING (true);

-- 4. Data migration block
DO $$
DECLARE
  r record;
  ing jsonb;
  v_ingredient_id bigint;
  v_ing_name text;
BEGIN
  -- Populate ingredients table with all unique ingredient names from existing mappings
  IF EXISTS (
    SELECT 1 
    FROM information_schema.tables 
    WHERE table_schema = 'public' 
      AND table_name = 'ingredient_mappings'
  ) THEN
    FOR r IN SELECT DISTINCT ingredient_name FROM public.ingredient_mappings LOOP
      INSERT INTO public.ingredients (name) 
      VALUES (r.ingredient_name)
      ON CONFLICT (name) DO NOTHING;
    END LOOP;
  END IF;

  -- Migrate recipes if recipe_data still exists
  IF EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'recipes' 
      AND column_name = 'recipe_data'
  ) THEN
    FOR r IN SELECT * FROM public.recipes LOOP
      -- Update recipes details
      UPDATE public.recipes
      SET
        name = COALESCE(r.recipe_data->>'name', 'Receta Sin Nombre'),
        meal_type = COALESCE(r.recipe_data->>'meal_type', 'comida'),
        price = COALESCE(r.recipe_data->>'price', 'economica'),
        difficulty = COALESCE(r.recipe_data->>'difficulty', 'facil'),
        health = COALESCE(r.recipe_data->>'health', 'saludable'),
        diet_type = COALESCE(r.recipe_data->>'diet_type', 'omnivoro'),
        allergens = ARRAY(SELECT jsonb_array_elements_text(COALESCE(r.recipe_data->'allergens', '[]'::jsonb))),
        instructions = ARRAY(SELECT jsonb_array_elements_text(COALESCE(r.recipe_data->'instructions', '[]'::jsonb)))
      WHERE id = r.id;

      -- Process ingredients
      IF r.recipe_data ? 'ingredients' THEN
        FOR ing IN SELECT * FROM jsonb_array_elements(r.recipe_data->'ingredients') LOOP
          v_ing_name := trim(ing->>'name');
          
          -- Ensure ingredient exists in public.ingredients
          INSERT INTO public.ingredients (name)
          VALUES (v_ing_name)
          ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
          RETURNING id INTO v_ingredient_id;

          -- Add to recipe_ingredients junction table
          INSERT INTO public.recipe_ingredients (
            recipe_id,
            ingredient_id,
            quantity,
            unit
          ) VALUES (
            r.id,
            v_ingredient_id,
            (ing->>'quantity')::numeric,
            ing->>'unit'
          )
          ON CONFLICT (recipe_id, ingredient_id) DO NOTHING;
        END LOOP;
      END IF;
    END LOOP;

    -- Set NOT NULL constraints
    ALTER TABLE public.recipes ALTER COLUMN name SET NOT NULL;
    ALTER TABLE public.recipes ALTER COLUMN meal_type SET NOT NULL;
    ALTER TABLE public.recipes ALTER COLUMN price SET NOT NULL;
    ALTER TABLE public.recipes ALTER COLUMN difficulty SET NOT NULL;
    ALTER TABLE public.recipes ALTER COLUMN health SET NOT NULL;
    ALTER TABLE public.recipes ALTER COLUMN diet_type SET NOT NULL;

    -- Drop old recipe_data column
    ALTER TABLE public.recipes DROP COLUMN recipe_data;
  END IF;
END $$;
