-- Create recipe_weights table
CREATE TABLE IF NOT EXISTS public.recipe_weights (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.recipes(id) on delete cascade not null,
  family_id uuid references public.family_units(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  weight integer default 0 not null,
  constraint recipe_weights_family_id_recipe_id_key unique (family_id, recipe_id),
  constraint recipe_weights_user_id_recipe_id_key unique (user_id, recipe_id),
  constraint recipe_weights_target_check check (
    (family_id is null and user_id is not null) or
    (family_id is not null and user_id is null)
  )
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.recipe_weights ENABLE ROW LEVEL SECURITY;

-- Define Policies for access and editing
DROP POLICY IF EXISTS recipe_weights_all ON public.recipe_weights;
CREATE POLICY recipe_weights_all ON public.recipe_weights
  FOR ALL
  TO authenticated
  USING (
    (family_id IS NOT NULL AND family_id IN (
      SELECT f.family_id FROM public.family_members f WHERE f.user_id = auth.uid()
    ))
    OR
    (user_id IS NOT NULL AND user_id = auth.uid())
  )
  WITH CHECK (
    (family_id IS NOT NULL AND family_id IN (
      SELECT f.family_id FROM public.family_members f WHERE f.user_id = auth.uid()
    ))
    OR
    (user_id IS NOT NULL AND user_id = auth.uid())
  );

-- Enable realtime subscriptions for recipe_weights
DO $$
BEGIN
  IF NOT EXISTS (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'recipe_weights'
  ) THEN
    alter publication supabase_realtime add table public.recipe_weights;
  END IF;
END $$;
